spring:
  application:
    name: outbox-store
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/outbox-pattern-db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'